drop table if exists `step` CASCADE;
drop table if exists `task` CASCADE;
create table `step` (
step_id integer generated by default as identity,
 complete boolean not null,
 name varchar(255), fk_task_id integer,
 primary key (step_id)
);
create table `task` (
id integer generated by default as identity,
descrition varchar(255), 
name varchar(255), 
primary key (id));